---

- name: VM setup
  hosts: aws_instances
  gather_facts: no

  tasks:   
  #Crea filesystem per la partizione docker
  - name: Formatting empy volume with XFS
    shell: sudo mkfs -t xfs /dev/xvdb && echo Present || echo Absent
    register: filesystem
    when: false
  
  #Crea directory per docker storage
  - name: Creating docker directory
    shell: sudo mkdir /{{ docker_path }} && echo Present || echo Absent
    register: docker_dir
    when: false
  
  #Monta directory
  - name: Mounting docker directory
    shell: sudo mount /dev/xvdb /{{ docker_path}} && echo Present || echo Absent
    register: mount_docker_dir
    when: false
    
  #Rendi persistente il montaggio anche in caso di reboot
  - name: Ensuring persistent mounting
    #get volume's UUID
    shell: sudo lsblk -f | grep -v xvda | awk '! /[AEJK]/ {print $3}'
    register: volume_UUID
  
  - name: debug
    debug:
      var: volume_UUID  
   
  #UUID=aebf131c-6957-451e-8d34-ec978d9581ae  /data  xfs  defaults,nofail  0  2

          


     
    
  